### PR TITLE
just added some tables

### PR DESCRIPTION
**Pull request by gregoryyoung**

### CODE REVIEW

**Comment by danleech** [comment]
I cocked up resolving conflicts a bit, but commits have been applied to gh-pages now (through an intermediary branch). If you can confirm that I’ll delete the fixes branch and close this PR.

**Comment by gregoryyoung** [comment]
I'll take a look.

On Tuesday, January 6, 2015, Dan Leech <notifications@github.com> wrote:

> I cocked up resolving conflicts a bit, but commits have been applied to
> gh-pages now (through an intermediary branch). If you can confirm that I’ll
> delete the fixes branch and close this PR.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/docs.geteventstore.com/pull/72#issuecomment-68860538>
> .
>


-- 
Studying for the Turing test

**Comment by gregoryyoung** [comment]
Hmm I'm not seeing my changes up on
http://docs.geteventstore.com/server/3.0.2-pre/metadata-and-reserved-names/
or are they still on a branch?

On Tuesday, January 6, 2015, Greg Young <gregoryyoung1@gmail.com> wrote:

> I'll take a look.
>
> On Tuesday, January 6, 2015, Dan Leech <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> I cocked up resolving conflicts a bit, but commits have been applied to
>> gh-pages now (through an intermediary branch). If you can confirm that I’ll
>> delete the fixes branch and close this PR.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/EventStore/docs.geteventstore.com/pull/72#issuecomment-68860538>
>> .
>>
>
>
> --
> Studying for the Turing test
>
>

-- 
Studying for the Turing test

**Comment by danleech** [comment]
Changes made now to that page.

**Pull request closed without merging**
